pasteurlabs/tesseract-core

- .pre-commit-config.yaml
- docs/content/creating-tesseracts/create.md
- tesseract_core/sdk/templates/jax/tesseract_api.py
Explained how to specify static numerical values in Jax recipe. Added clarifications to docs warning on Differentiable.
N/A
<details>
```text
Version 1.1
of my knowledge, is covered under an appropriate open …
```
> doc: Updated comments in jax recipe and docs on Differentiable flag

- tesseract_core/sdk/tesseract.py
- tests/sdk_tests/test_tesseract.py
Close #19 
If HTTPClient gets a 422 response (validation error), its context is parsed and reraised as a pydantic ValidationError
Added a unit test + tested locally on vectoradd with
```python
from tesseract_core import Tesseract
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = np.array([1.0, 2.0, 3.0])
with Tesseract.from_image("vectoradd") as t:
t.apply({"whoops": "whatever"})
```
- [ x] By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://pasteurlabs.github.io/tesseract/LICENSE).
- [ x] I sign the Developer Certificate of Origin below by adding my name and email address to the `Signed-off-by` line.
<details>
```text
Version …
```
> feat: Raise proper error (`ValidationError`) for invalid inputs

- examples/vectoradd_jax/tesseract_api.py
- tesseract_core/sdk/templates/jax/tesseract_api.py
- tests/endtoend_tests/test_examples.py
Fix #74 
Check that x in is_leaf(x) is a dict before calling methods like .keys()
Local checks, added e2e test
- [ x] By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://pasteurlabs.github.io/tesseract/LICENSE).
- [ x] I sign the Developer Certificate of Origin below by adding my name and email address to the `Signed-off-by` line.
<details>
```text
Version 1.1
By making a contribution to this project, I …
```
> fix: Issue #74

- tesseract_core/sdk/tesseract.py
There was no way to query `abstract_eval` with  `tesseract_core.Tesseract`; this fixes it
Added a method to `tesseract_core.Tesseract`.
Tested locally against `vectoradd_jax` with the following script
<details>
```text
Version 1.1
(b) The contribution is based upon previous …
```
> feat: Add `abstract_eval` method to `tesseract_core.Tesseract`

- CHANGELOG.md
Bump changelog in preparation of a release
`git cliff --output CHANGELOG.md --bump` + small manual edit
👁️ + 👁️  + 👓 
<details>
```text
Version 1.1 …
```
> chore: Bump changelog for v0.7.3

- CHANGELOG.md
- cliff.toml
prepare for v0.7.4
`git cliff --output CHANGELOG.md`
<details>
```text
Version 1.1
license and I have the right under that license to submit that …
```
> chore: Update changelog

- tesseract_core/runtime/schema_generation.py
- tests/runtime_tests/test_schema_generation.py
n/a
Before this PR, requesting the OpenAPI schema of a Tesseract that uses a differentiable array of unknown rank would trigger a serialization error:
```python
class InputSchema(BaseModel):
myarray: Differentiable[Array[..., Float32]]
```
```bash
$ tesseract-runtime input-schema
...
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'ellipsis'>
```
The problem is that `...` was inserted as shape into the new `differentiable_arrays` property of the schema, which works as long as the schema isn't serialized to JSON (which we didn't test for).
CI, old and new tests
<details>
```text
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its …
```
> fix: OpenAPI schema failure for differentiable arrays with unknown shape

- tesseract_core/sdk/templates/Dockerfile.base
Fixes #101 
☝️ 
CI
<details>
```text
Version 1.1
license and I have the right under that license to submit that
work with modifications, whether …
```
> fix: use fixed uid/gid 5000:5000 for all tesseracts

- tesseract_core/sdk/templates/Dockerfile.base
I was informed that 1000 is a more common value than 5000, so we should use that as the default to avoid permission issues in most cases.
<details>
```text
Version 1.1
of my knowledge, is covered under an …
```
> fix: use uid 1000 instead of 5000

- requirements.txt
- tesseract_core/runtime/experimental.py
- tesseract_core/runtime/meta/pyproject.toml
- tesseract_core/runtime/meta/requirements.txt
- tesseract_core/runtime/schema_generation.py
- tesseract_core/runtime/schema_types.py
n/a
- Make tests pass with new pydantic.
- Upper bound all runtime dependencies.
CI
<details>
```text
Version 1.1
license and I have the right under …
```
> fix: Pydantic 2.11.0 compatibility (hotfix)

- .readthedocs.yaml
<details>
```text
Version 1.1
license and I have the right under that license to submit that
work with modifications, whether created in whole or in …
```
> chore: fix readthedocs config

- examples/meshstats/tesseract_api.py
- tests/endtoend_tests/test_examples.py
n/a
Noticed that meshstats `abstract_eval` is wrong (crashes), so I fixed it + added a test.
CI, new test
<details>
```text
Version 1.1
license and I …
```
> fix: meshstats `abstract_eval`

- tesseract_core/sdk/tesseract.py
- tests/sdk_tests/test_tesseract.py
n/a
- Ensure returned arrays have the correct shape and dtype.
- Fix an internal error when triggering certain validation errors that rely on a context object.
manual
<details>
```text
Version 1.1
of my …
```
> fix: Fix Tesseract SDK decoding and error handling

- tesseract_core/sdk/tesseract.py
- tests/sdk_tests/test_tesseract.py
n/a
Also allow passing an imported module to `Tesseract.from_tesseract_api`. For example, this allows users to monkeypatch or construct modules at runtime without having to write them to a file.
new test on CI
<details>
```text
Version 1.1
(b) The contribution is based upon …
```
> feat: also allow passing an imported module to Tesseract.from_tesseract_api

- tesseract_core/sdk/templates/jax/tesseract_api.py
N/A
Fixed typos in jax recipe
Manual: Initializing Tesseract with jax recipe generates running code without typos
<details>
```text
Version 1.1 …
```
> fix: fixed typos in jax recipe

- .github/workflows/run_tests.yml
n/a
This allows us to mark all tests as required to merge a PR.
👇 ([all-ok](https://github.com/pasteurlabs/tesseract-core/actions/runs/14900366944/job/41851192798?pr=153) ran)
<details>
```text
Version 1.1
of …
```
> chore: add all-ok test step

- tesseract_core/sdk/cli.py
apidoc call failed due to using a container ID in place of a Container object when retrieving the doc's host port:
```
│ /usr/local/lib/python3.12/dist-packages/tesseract_core/sdk/cli.py:563 in apidoc                  │
│                                                                                                  │
│   560 │   try:                                                                                   │
│   561 │   │   project_id = engine.serve([image_name])                                            │
│   562 │   │   container = docker_client.compose.list()[project_id][0]                            │
│ ❱ 563 │   │   url = f"http://localhost:{container.host_port}/docs"                               │
│   564 │   │   logger.info(f"Serving OpenAPI docs for Tesseract …
```
> fix: apidoc CLI call used container ID in place of container object to retrieve host port

- tesseract_core/sdk/engine.py
#157 
Added FileNotFound exception to `needs_docker` wrapper
Completely uninstalled docker and triggered the FileNotFoundError / no docker command error.
Reinstalled package with change and now we get this error instead.
```
(tesseract) 柯 ~/work/tesseract-core » tesseract build examples/empty
[-] Docker daemon is not running, check if it is installed.
[x] Aborting
```
> fix: Add FileNotFoundError to docker info

- tesseract_core/sdk/docker_client.py
n/a
Wrong order of arguments, we passed `docker build -- <contextdir> --ssh ...` but it should be `docker build --ssh ... -- <contextdir>`.
none yet
> fix: "docker buildx build requires exactly 1 argument" error when using `tesseract build --forward-ssh-agent`

- .github/workflows/run_tests.yml
- docs/content/using-tesseracts/advanced.md
- tesseract_core/sdk/cli.py
- tesseract_core/sdk/docker_client.py
- tesseract_core/sdk/engine.py
- tesseract_core/sdk/tesseract.py
- tests/dummy_tesseract/tesseract_api.py
- tests/endtoend_tests/test_endtoend.py
- tests/sdk_tests/test_tesseract.py
@johnbcoughlin extracted this from #229 . It's needed right away and requires less discussion, so makes sense to merge separately.
We allow passing user-defined env variables to docker (and docker-compose) on `tesseract run` and `tesseract serve`.
Example:
```
tesseract run --env=MLFLOW_TRACKING_URI="http://localhost:5001" helloworld apply '...'
```
Immediately relevant use case: Connecting tesseracts to user-hosted MLflow servers.
Tested manually.
> feat: pass env variables through `tesseract run` and `tesseract serve`

- tesseract_core/sdk/cli.py
- tesseract_core/sdk/engine.py
The `network` argument was implemented in `tesseract run` but not `tesseract serve`
Added `network` arg and piped it to docker
> feat: Add network argument to `tesseract serve`

- tesseract_core/sdk/docker_client.py
- tesseract_core/sdk/engine.py
n/a
- Add functionality to restart containers if they exit unexpectedly (same as we did with `docker-compose`).
- Distinguish between a container failing to start and taking too long to start.
- Improve error messages.
- Call `get_config()` in every function of the Docker client instead of at import time (config may change during runtime).
manual
> feat: improve healthcheck after serve, add restart policy

- examples/_multi-tesseract/multi_helloworld/README.md
- examples/_multi-tesseract/multi_helloworld/run_example.py
- tesseract_core/sdk/tesseract.py
- tests/endtoend_tests/test_examples.py
- tests/sdk_tests/test_tesseract.py
- Added network arguments to `from_image` method of `tesseract_core.sdk.tesseract.Tesseract`
- Updated "multi-helloworld" examples to make use of network aliases
- Fixed a couple of typos in `tesseract_core.sdk.tesseract`
- Local testing of example CLI and SDK instructions
- "multi-helloworld" e2e test passes
> feat: add network args to from_image

- tesseract_core/sdk/tesseract.py
We now support running Tesseracts via `from_image` without context manager, by explicitly spinning the Tesseract up on `.serve()` instead.
The error message still conveyed that context managers are the only option.
Local testing
> fix: Correct error message on use of T created via from_image

- tests/endtoend_tests/test_tesseract_sdk.py
Adds an automated test of the invariant asked for in the comments on `LogPipe`:
```
```
> fix: Test that LogPipe implementations do not diverge

- tesseract_core/runtime/array_encoding.py
- tesseract_core/runtime/cli.py
- tesseract_core/runtime/core.py
- tesseract_core/runtime/experimental.py
- tesseract_core/runtime/file_interactions.py
- tesseract_core/runtime/mpa.py
- tesseract_core/runtime/serve.py
- tests/conftest.py
- tests/endtoend_tests/test_endtoend.py
- tests/runtime_tests/test_mpa.py
- tests/runtime_tests/test_serve.py
n/a
This adopts a new folder structure for outputs.
**Using `tesseract run`:**
```bash
$ tesseract run metrics apply '{"inputs": {}}' --output-path /tmp/t_run --output-file out.json
This is a message from the apply function.
$ tree /tmp/t_run
/tmp/t_run
├── logs
│   ├── artifacts
│   │   └── artifact.txt
│   ├── metrics.csv
│   ├── parameters.json
│   └── tesseract.log
├── out.json
└── <optional .bin files when using binref>
$ tesseract run metrics apply '{"inputs": {}}' --output-path /tmp/ml_run --output-file out.json --output-format json+binref --env TESSERACT_MLFLOW_TRACKING_URI=/tesseract/output_data/mlruns
This is a message from the apply function.
$ tree /tmp/ml_run
/tmp/ml_run
├── logs
│   └── tesseract.log
├── mlruns
│   └── 0
│       ├── b27ad9c511f241569678d44159f0cc8a
│   …
```
> refactor: transpose folder structure

- tesseract_core/sdk/api_parse.py
- tests/sdk_tests/test_api_parse.py
Currently, tesseracts are not allowed to have digits in the pre-release section of the version/tag. This changes that behavior to allow that, e.g. `1.2.3-rc2`.
Tested manually:
```console
$ uv run tesseract build --tag 1.2.3-rc2 examples/vectoradd
[i] Building image ...
[i] Built image sha256:41b380c24c95, ['vectoradd:1.2.3-rc2']
["vectoradd:1.2.3-rc2"]
```
> fix: allow digits in the pre-release semver tag
